[api]
host = "0.0.0.0"
port = 8000
secret_key = "${SECRET_KEY}"

[slack]
debug = "${SLACK_DEBUG|false}"
bot_id = "${SLACK_BOT_ID}"
access_token = "${SLACK_ACCESS_TOKEN}"
verification_token = "${SLACK_VERIFICATION_TOKEN}"
signing_secret = "${SLACK_SIGNING_SECRET}"

[elastic]
host = "${ELASTIC_HOST|localhost}"
port = "${ELASTIC_PORT|9200}"

[logger]
level = "debug"
